GET http://localhost:3300/api/v1/opd

### create user
POST http://localhost:5252/

### get user by id
GET  http://localhost:5252/Kabko

### update user by id
PATCH  http://localhost:5252/user/id

### delete user by id
DELETE  http://localhost:5252/user/id

### create Kabko
POST http://localhost:5252/Kabko
Content-Type: application/json

{
    "nama" : "Kab. Perawang barat3",
    "foto" : "perawang.png",
    "web"  : "#"
}